@host=http://localhost:8080

### Health Check
GET {{host}}/health
Content-Type: application/json

### Create Order
POST {{host}}/api/v1/orders
Content-Type: application/json

{
  "customer_id": "19b5408e-8ee2-47d4-953b-196d41f1e367"
}

### Get order by ID
GET {{host}}/api/v1/orders/cd60eb78-53fb-4dd4-93ee-3fc3ef437c1c
Content-Type: application/json

### Get order by Tack ID
GET {{host}}/api/v1/orders/tracking/UVW-938
Content-Type: application/json

### Get order by Customer ID
GET {{host}}/api/v1/orders/customer/19b5408e-8ee2-47d4-953b-196d41f1e367
Content-Type: application/json

### Add item to the order
POST {{host}}/api/v1/orders/cd60eb78-53fb-4dd4-93ee-3fc3ef437c1c/items
Content-Type: application/json

{
  "items": [
    {
      "id": "b88014db-320d-4ac9-99b1-422774d56106",
      "name": "Product 1",
      "unit_price": 10.5,
      "quantity": 1
    }
  ]
}

### Send order to payment topic
POST {{host}}/api/v1/orders/cd60eb78-53fb-4dd4-93ee-3fc3ef437c1c/payment
Content-Type: application/json

### Update order
PATCH {{host}}/api/v1/orders/cd60eb78-53fb-4dd4-93ee-3fc3ef437c1c
Content-Type: application/json

{
  "state": 2
}