version: '3.8'

services:
  order_db:
    image: postgres:16.0
    container_name: order_db
    volumes:
      - ./scripts/database:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: "order_db"
      POSTGRES_USER: "order"
      POSTGRES_PASSWORD: "order"
    ports:
      - "5432:5432"
    networks:
      - api-network
  
  pgadmin:
    depends_on:
      - order_db
    image: dpage/pgadmin4:7.8
    container_name: pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  pgadmin-data: