apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-order-management-config
  namespace: ns-orders
  labels:
    app: ms-order-management
data:
  API_PORT: "8080"
  API_ENV_NAME: production
  API_VERSION: v1
  DB_NAME: orders
  DB_URL: todo
  DB_URL_SECRET_NAME: db-orders-url-secret
  AWS_ORDER_PAYMENT_TOPIC_NAME: OrderPaymentTopic
  AWS_UPDATE_ORDER_QUEUE_NAME: UpdateOrderQueue