apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-order-management-ingress
  namespace: ns-orders
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /orders-mgmt(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ms-order-management
                port:
                  number: 8080