apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-order-management-ingress
  namespace: ns-orders
spec:
  rules:
    - http:
        paths:
          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: ms-order-management
                port:
                  number: 8080