// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockProcessMessageService is an autogenerated mock type for the ProcessMessageService type
type MockProcessMessageService[T interface{}] struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, message
func (_m *MockProcessMessageService[T]) Handle(ctx context.Context, message T) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockProcessMessageService creates a new instance of MockProcessMessageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessMessageService[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessMessageService[T] {
	mock := &MockProcessMessageService[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
